### ISSUE TITLE
Synchronizer.js

### ISSUE THREAD

**Issue by tristan2583** [danvk/dygraphs#610]
Hi danvk!
I'm using dygraphs mainly for the synchronization feature so I need to use synchronizer.js.

First of all it's not clear where to find syncronizer.js. I've used that on GitHub (https://github.com/danvk/dygraphs/blob/master/src/extras/synchronizer.js) and It doesn't work.
I get stucked on that problem when trying to syncronize a few graphs:

Uncaught TypeError: gs[i].getRowForX is not a function (17:04:31:245 | error, javascript)
    at g.updateOptions.highlightCallback (public_html/js/dygraph/extras/synchronizer.js:184:27)
    at Dygraph.mouseMove_ (public_html/js/dygraph/dygraph-combined-dev.js:3972:14)
    at Dygraph.createInterface_.mouseMoveHandler_ (public_html/js/dygraph/dygraph-combined-dev.js:3127:13)

So I decided to copy the synchronizer.js used on demo gallery and all works fine.

**Comment by danvk** [comment]
You're running into version mismatch. The `synchronizer.js` on GitHub is tracking all recent changes to dygraphs, whereas the version on the dygraphs.com web site is pinned to the most recent release (1.1.0).

The point about clearer documentation is well-taken, though.

**Comment by nejcb1** [comment]
It would be nice, if you put right version on GitHub, so there will be no version mismatch.

**Comment by Ggleny** [comment]
Hi!, When do you create a new version in web site, with all changes from GitHub?
